# -*- coding: utf-8 -*-
"""run_climate_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ewPOjURGx6XTH7ZlvaQJKDrL8-DkuOx
"""

!pip install -q transformers datasets scikit-learn

from datasets import load_dataset
import pandas as pd, random

ds = load_dataset("amandakonet/climate_fever_adopted", split="test")
print(ds)
print(ds[0])

df = pd.DataFrame(ds).sample(30, random_state=42).reset_index(drop=True)
df.to_csv("climate_claims_sample.csv", index=False)
print(df.columns.tolist())
df.head()

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch, time

model_name = "amandakonet/climatebert-fact-checking"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)
model.eval()

print("Label mapping from model config:")
print(model.config.id2label)

label_align = {
    "LABEL_0": "SUPPORTS",
    "LABEL_1": "REFUTES",
    "LABEL_2": "NOT_ENOUGH_INFO",
}

preds = []
start = time.time()
for _, row in df.iterrows():
    inputs = tokenizer(row["claim"], row["evidence"], return_tensors="pt", truncation=True)
    with torch.no_grad():
        logits = model(**inputs).logits
    pred_id = logits.argmax(-1).item()
    raw_label = model.config.id2label[pred_id]
    preds.append(raw_label)
runtime_seconds = time.time() - start

df["predicted_label_raw"] = preds
df["predicted_label"] = df["predicted_label_raw"].map(label_align)
print(f"Runtime: {runtime_seconds:.2f}s")
df.head(10)

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

def classification_metrics(y_true, y_pred):
    true, pred = list(y_true), list(y_pred)
    return {
        "accuracy": float(accuracy_score(true, pred)),
        "macro_f1": float(f1_score(true, pred, average="macro", zero_division=0)),
        "macro_precision": float(precision_score(true, pred, average="macro", zero_division=0)),
        "macro_recall": float(recall_score(true, pred, average="macro", zero_division=0)),
    }

metrics = classification_metrics(df["evidence_label"], df["predicted_label"])
print("METRICS:", metrics)

for name, value in metrics.items():
    df[name] = value
df["model_name"] = "amandakonet/climatebert-fact-checking"
df["runtime_seconds"] = runtime_seconds
df["sample_size"] = len(df)

# ============================================================
# CELL 7 — Error analysis (misclassified examples for your report)
# ============================================================

errors = df.loc[
    df["evidence_label"] != df["predicted_label"],
    ["claim", "evidence", "evidence_label", "predicted_label"]
]

print(f"Misclassified: {len(errors)} out of {len(df)} rows")
print(f"Error rate: {len(errors)/len(df):.2%}")

errors

df["model_name"] = "amandakonet/climatebert-fact-checking"
df["runtime_seconds"] = runtime_seconds
df["sample_size"] = len(df)

df.to_csv("results.csv", index=False)
print("Saved results.csv")
print(df[["accuracy", "macro_f1", "macro_precision", "macro_recall"]].iloc[0])

from google.colab import files
files.download("results.csv")
files.download("climate_claims_sample.csv")